### ISSUE TITLE
factor as.factor(day_of_week) has new levels using predict_gam(model)

### ISSUE THREAD

**Issue by rebootcat** [stefanocoretta/tidygam#2]
Hi, Coretta:
I tried to using predict_gam with the fitted gam model like this:
```
model <- gam(
  duration ~
    s(tem_max) +
    s(day_cross_year) + as.factor(day_of_week),
  data = data
) 
summary(model)  
plot(model, scale = 0, pages = 1, shade = T)
model_p <- predict_gam(model)
model_p
```
when I remove "as.factor(day_of_week)", it's work quite well. However error like this appeared with "as.factor(day_of_week)"
```
Error in model.frame.default(Terms[[i]], data, xlev = object$xlevels) : 
  factor as.factor(day_of_week) has new levels 1.6, 2.2, 2.8, 3.4, 4.6, 5.2, 5.8
```

all variables in data is numeric. So how to fix it? 
HELP😣😣

**Comment by stefanocoretta** [comment]
Hi! Thanks for giving the package a spin!

Can you try and convert `day_of_week` to a factor in the data frame before specifying the data in the model, rather than converting it to factor in the model formula?

**Comment by rebootcat** [comment]
Thanks for your help. Convert to factor before fit worked.
