### ISSUE TITLE
R studio desktop/server crashed with complex gam

### ISSUE THREAD

**Issue by rebootcat** [stefanocoretta/tidygam#3]
The original gam is
```
fit <- gam(
  duration ~
    s(x1) +
    s(x2) +
    s(x3) +
    s(x4) +
    s(x5) +
    s(x6) +
    as.factor(day_of_week) +
    as.factor(holiday) +
    as.factor(month) +
    as.factor(season),
  data = data
)
```

However it seems too many variable costs much memory when I did this
```
data$day_of_week <- as.factor(data$day_of_week)
data$holiday <- as.factor(data$holiday)
data$month <- as.factor(data$month)
data$season <- as.factor(data$season)

model <- gam(
    duration ~
    s(x1) +
    s(x2) +
    s(x3) +
    s(x4) +
    s(x5) +
    s(x6) +
    day_of_week +
    holiday +
    month +
    season,
  data = data
)
summary(model)
plot(model, shade = T, pages = 1, scale = 0)

model_p <- predict_gam(model)
model_p
```

I tried this in Mac with 16Gb memory and "Memory usage exceeds limits" happened. So I tried in Ubuntu 20 with 32Gb memory. R studio crashed with "unexpected error happened".
I guess this caused by memory out of usage. But using machine with more memory seems not elegant.

I have to remove some variable. It worked but we need those removed variables.
```
data$day_of_week <- as.factor(data$day_of_week)
data$holiday <- as.factor(data$holiday)
data$month <- as.factor(data$month)
data$season <- as.factor(data$season)

model <- gam(
    duration ~
    s(x1) +
    day_of_week +
    holiday +
    month +
    season,
  data = data
)
summary(model)
plot(model, shade = T, pages = 1, scale = 0)

model_p <- predict_gam(model)
model_p
plot(model_p, series = c("x1"))
```

**Comment by rebootcat** [comment]
`fit` and `se.fit` are not included in tidygam, so I choose tifymv instead.

**Comment by stefanocoretta** [comment]
I am not sure what the issue is here. It would be helpful if you'd provided a minimal working example I can run.

**Comment by rebootcat** [comment]
sorry for reply so late. I have changed research topic following my supervisor. So I have to put gam on hold until his program been restarted.
